import type { Metadata } from 'next'
import { Montserrat as FontSans } from 'next/font/google'
import '../../shared/globals.css'
import { cn } from '@/shared/lib'
import { ThemeProvider } from '@/entities/theme'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru' style={{ colorScheme: 'light' }} suppressHydrationWarning>
			<body className={cn(' min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
				<ThemeProvider attribute='class' defaultTheme='light'>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
